### PR TITLE
Added Feedback and rating

### PR DESCRIPTION
**Pull request by daksh1210jain**
Added feedback and rating system to the website 
under JWOC 
for issue #57

### CODE REVIEW

**Comment by daksh1210jain** [comment]
Kindly accept the PR

**Review by ritika728 — COMMENTED** [review]
The rating page currently lacks content, a navigation bar, and a footer. In accordance with the theme of the other pages, please get the above mentioned things added.
Also, kindly add the 'Rate Us'  in the navbar of all the existing pages

**Comment by daksh1210jain** [comment]
Mam please have a look again

**Comment by daksh1210jain** [comment]
mam added things you said kindly have a look

**Comment by ritika728** [comment]
@daksh1210jain the deployed link won't work as you have moved the index.html file. Also, the home page is distorted because of this movement. Kindly get it back to its previous place. Rest, faq page looks good

**Comment by daksh1210jain** [comment]
mam i dont see any distortion in the home page . can you please elaborate on that
and also i dont see any error in the code along with that the checks have also passed 
Kindly let me know what needs to be done

**Comment by ritika728** [comment]
This is the deployed link after the changes you've made:
https://wellness-wave-18u3diwqs-ritika-maliks-projects.vercel.app/
You'll get this upon opening it:

This is happening because you have moved index.html file in the html files folder. Moreover, if you'll check it on your local system, the various links integrated on the homepage (for eg. navbar, faq, t&c etc.) won't work since the navigation is changed.

See the file structuring in the current main repository. You just need to move index.html out of the folder.

**Pull request closed without merging**
