### PR TITLE
Freshcal

### PR DESCRIPTION
**Pull request by isadarsh**

### CODE REVIEW

**Comment by isadarsh** [comment]
closes #12

**Comment by ritika728** [comment]
@isadarsh the body fat calculator is occupying the entire page. Please reduce the dimensions so that it resembles to the UI of other calculator pages. Rest, the water-intake calculator seems good.

**Comment by isadarsh** [comment]
update the ui of body fat calculator..

**Review by ritika728 — APPROVED** [review]
Looks good to merge
Thank you for contributing!

**Pull request merged**
