### PR TITLE
added reset button feature to all the calculators in tracking section

### LINKED ISSUE #129: Add RESET button
### Describe
I would like to add RESET button to all the calculators , under tracking section .

### Screenshots

**CheckList**
- [X] I'm a JWOC'24 Contributor
- [X] I've checked the existing issues, this issue is not a duplicate

### PR DESCRIPTION
**Pull request by madhurima316**
close #129

### CODE REVIEW

**Comment by ritika728** [comment]
@madhurima316 the button isn't returning the expected result when clicked, kindly look into it

**Comment by madhurima316** [comment]
can you please explain what specific change or result do you expect because the RESET buttons are working properly as I intended - that is clearing the texts of input boxes ,on the present screen (calculator) .

**Comment by ritika728** [comment]
@madhurima316 upon clicking the button, the output is clearing, but the input provided in the respective fields remains the same. It isn't clearing out.

**Comment by ritika728** [comment]
https://github.com/ritika728/Wellness_Wave/assets/91181981/10a3f54f-d4d2-4acc-8e50-e79bb847d8ea

**Comment by madhurima316** [comment]
ma'am , but the reset buttons are working fine, for me .

https://github.com/ritika728/Wellness_Wave/assets/145414858/61150acf-7175-4b82-bcc7-70130a60b6ea
https://github.com/ritika728/Wellness_Wave/assets/145414858/0377ed41-587b-424f-b52e-c01616d39f0b

**Review by ritika728 — APPROVED** [review]

**Pull request merged**
