### PR TITLE
Blood Pressure Calculation

### PR DESCRIPTION
**Pull request by swetasingh8844**
I made Blood Pressure Calculator .
This is what the page looks like!!
image

### CODE REVIEW

**Comment by swetasingh8844** [comment]
image
this is the page

**Comment by ritika728** [comment]
@swetasingh8844 this is not in consistent with the theme of other calculators. Kindly check them 
Also, you'll have to add this calculator in the fitness tracking file.

**Comment by swetasingh8844** [comment]
image
is this fine?

**Review by ritika728 — APPROVED** [review]
Yes, looks good to merge
Thank you for contributing

**Pull request merged**
