### PR TITLE
Heart rate calculator

### PR DESCRIPTION
**Pull request by GhoshAditi**
issue #86 
Added heart rate calculator
Un1titled

image

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@ritika728 plz check

**Review by ritika728 — COMMENTED** [review]
The calculator is occupying the whole page. Please adjust the margins accordingly. Rest, its good 👍

**Comment by GhoshAditi** [comment]
@ritika728 hope this one is ok
image
plz check

**Comment by ritika728** [comment]
Yes, looks good to merge
Thank you for contributing

**Pull request merged**
