### PR TITLE
Created a light and dark mode button in all pages

### PR DESCRIPTION
**Pull request by Sneha123-zudo**
#74 Added a light and dark mode button in all pages , please review my pull reuest.

### CODE REVIEW

**Comment by ritika728** [comment]
@Sneha123-zudo please resolve the conflicts

**Comment by Sneha123-zudo** [comment]
Done , please have a look now.

**Comment by ritika728** [comment]
@Sneha123-zudo the UI of the original site is changed in tracking, wellness & FAQ Pages, which is not looking appealing. Moreover, the header of the tracking page & rating page are distorted. 

Please keep the UI as it was, & resolve the distortion in the above mentioned pages

**Comment by ritika728** [comment]
@Sneha123-zudo the UI of the original site is changed in tracking, wellness & FAQ Pages, which does not look appealing. Moreover, the rating page & the header of the tracking page are distorted.

Please keep the UI as it was, & resolve the distortion in the above mentioned pages

**Pull request closed without merging**
