### PR TITLE
navbar style improved

### LINKED ISSUE #139: [STYLE] add new navbar
### Describe
add new nav bar 

### Screenshots
Current  
cc

new 

nn

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

### PR DESCRIPTION
**Pull request by AftabMankapure**
fixed #139 
close #139 

Video 

https://github.com/ritika728/Wellness_Wave/assets/125949765/f8588bbf-6a5d-4c6d-a4dd-fda5b8e72275

### CODE REVIEW

**Comment by AftabMankapure** [comment]
pls check this PR

**Comment by ritika728** [comment]
@AftabMankapure please resolve the conflict

**Comment by AftabMankapure** [comment]
check this

**Comment by ritika728** [comment]
@AftabMankapure Incorporate the changes in the index page as well.

**Comment by AftabMankapure** [comment]
check nav

**Comment by ritika728** [comment]
@AftabMankapure consider checking it on your local system

**Review by ritika728 — APPROVED** [review]

**Pull request merged**
